[discord]
token = "NDAxNTA3MzM4MDEzNjM4NjU2.DTsS0g.ecDa_xEL4nbsL0V1msVa0ppFIbw"

[[commands]]
prefix = "Qdnp"
aliases = [ "Qdcp" ]

[[commands]]
prefix = "Qdprev"

[[commands]]
prefix = "Qdnext"

[voice]
passes = 2
bitrate = 44100

[emoji]
twitter = "<:twitter:373576839085686804>"
youtube = "<:youtube:374131863427743774>"
soundcloud = "<:soundcloud:374132011486674944>"
facebook = "<:facebook:374140079482077184>"
periscope = "<:periscope:374140311934337025>"
mixcloud = "<:mixcloud:375688433844092938>"

[soundcloud]
client_id = "soundcloud_client_id"

[youtube]
token = "youtube_token_here"

[[radios]]
token = "radio_bot_1_token"
channel = "330121740758024193"
name = "Q-Dance Radio"
url = "http://perseus.shoutca.st:9253/stream"
